# -*- coding: utf-8 -*-
"""Plaintexttoppt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wJb2tpDcZU2HXlpf8AqC8M1H886igTyQ
"""

# Plain Text	to PPTX (PowerPoint)	using python-pptx
# Step 1: Install required package
!pip install python-pptx --quiet

# Step 2: Upload your .txt file
from google.colab import files
uploaded = files.upload()  # Upload a .txt file (e.g., notes.txt)

# Step 3: Read the uploaded file
filename = next(iter(uploaded))
with open(filename, 'r') as file:
    text_lines = file.read().splitlines()

# Step 4: Create PowerPoint slides from text
from pptx import Presentation
from pptx.util import Inches, Pt

# Create presentation
prs = Presentation()
slide_layout = prs.slide_layouts[1]  # Title + Content

# Split into slides (e.g., 5 lines per slide)
lines_per_slide = 5
for i in range(0, len(text_lines), lines_per_slide):
    slide = prs.slides.add_slide(slide_layout)
    title = slide.shapes.title
    body = slide.placeholders[1]

    title.text = f"Slide {i // lines_per_slide + 1}"
    body.text = '\n'.join(text_lines[i:i + lines_per_slide])

# Step 5: Save and download PPTX
output_file = "text_to_pptx_output.pptx"
prs.save(output_file)
files.download(output_file)